version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs,apigateway
    ports:
      - '4566-4583:4566-4583'